{
  "headers": {
    "content-type": "application/json",
    "client_id": "<string>",
    "client_secret": "<string>",
    "user-agent": "PostmanRuntime/7.32.2",
    "accept": "*/*",
    "postman-token": "dbcb5897-6850-4311-9a74-32ca07cbf85a",
    "host": "localhost:8081",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "484"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "https",
  "queryParams": {},
  "requestUri": "/api/reserve-timeslot",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/reserve-timeslot",
  "listenerPath": "/api/*",
  "relativePath": "/api/reserve-timeslot",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/api/reserve-timeslot",
  "rawRequestPath": "/api/reserve-timeslot",
  "remoteAddress": "/127.0.0.1:60502",
  "requestPath": "/api/reserve-timeslot"
}